### PR TITLE
Add returns to fix missing_return errors with 2.10.0-dev.1.0.

### PR DESCRIPTION
**Pull request by keertip**

### CODE REVIEW

**Comment by keertip** [comment]
@tvolkert

**Review by goderbauer — APPROVED** [review]
LGTM

Do we need to bump the version number to publish this?

**Review by tvolkert — APPROVED** [review]

**Comment by keertip** [comment]
yes, will upload changes to pubspec and CHANGELOG

**Comment by tvolkert** [comment]
Yeah, you need to bump the test dependency to `^1.0.0` too

**Review by tvolkert — APPROVED** [review]
LGTM

**Pull request merged**
