### PR TITLE
Make encoding parameter nullable (again)

### PR DESCRIPTION
**Pull request by lambda-fairy**
Re-do of #65.

Require Dart SDK >= 2.14.0, as that's the first release to include the needed fix (dart-lang/sdk@5de7dfb90bf1d006c64992938a9e2a2a0908d4d4).

cc #64

### CODE REVIEW

**Comment by lambda-fairy** [comment]
```
    info - lib/src/interface/local_process_manager.dart:18:8 - The import of 'exceptions.dart' is unnecessary because all of the used elements are also provided by the import of 'package:process/process.dart'. Try removing the import directive. - unnecessary_import
   info - lib/src/interface/local_process_manager.dart:19:8 - The import of 'process_manager.dart' is unnecessary because all of the used elements are also provided by the import of 'package:process/process.dart'. Try removing the import directive. - unnecessary_import
```

These warnings seem unrelated to my change – should I ignore them?

**Comment by lambda-fairy** [comment]
Hey @tvolkert, would you like to have a look?

**Comment by tvolkert** [comment]
> These warnings seem unrelated to my change – should I ignore them?

You might as well remove the superfluous imports while you're in there.

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by lambda-fairy** [comment]
> You might as well remove the superfluous imports while you're in there.

Done 🙂

**Pull request merged**
