### PR TITLE
Update intl version range

### PR DESCRIPTION
**Pull request by jonahwilliams**
Flutter needs this constraint updated so we can roll new versions of intl and devtools

### CODE REVIEW

**Comment by jonahwilliams** [comment]
cc @tvolkert @goderbauer

**Review by tvolkert — APPROVED** [review]
You'll want to bump the version of this package and put in a CHANGELOG entry as well.

**Comment by jonahwilliams** [comment]
Woops, done

**Comment by tvolkert** [comment]
`3.0.12` published!

**Comment by jonahwilliams** [comment]
Thank you!

**Pull request merged**
