### PR TITLE
Add a specific type to the map method in _getArguments 

### PR DESCRIPTION
**Pull request by a-siva**
Add a specific type to the map method in _getArguments to work around
issue https://github.com/dart-lang/sdk/issues/32414

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by a-siva** [comment]
@goderbauer I do not seem to have write access to this package, can you land the patch for me. Thanks.

**Comment by goderbauer** [comment]
Of course. Done.

**Comment by a-siva** [comment]
Thanks,

**Comment by goderbauer** [comment]
It's live on pub now as well: https://pub.dartlang.org/packages/process

**Pull request merged**
